### ISSUE TITLE
Calculation of Plunder does not match up

### ISSUE THREAD

**Issue by hduyker** [izzymg/Plunderstorm-Calc#1]
Hi, cool app!

However, there's a "bug" in the calculation of Plunder.

I was (am) tracking my "rounds" in a GSheet (mostly for plunder/minute, but also to see how much time I was ~~wasting~~ spending in the game and such, average round length, what # I ended up with, etc., and I had a similar calculation.

And I discovered that, yes, it's 2500 per Rank. _**Except for the first**_, which is 1500.

So when I put in my data, I see that I'm 1000 Plunder off.

**Comment by izzymg** [comment]
Hey, thanks so much for this! 1,500 for the first level seems perfect accuracy - deploying the new build now with the improved estimation.
